// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: test.proto
#ifndef GRPC_test_2eproto__INCLUDED
#define GRPC_test_2eproto__INCLUDED

#include "test.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace test {

class testService final {
 public:
  static constexpr char const* service_full_name() {
    return "test.testService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status TestGrpc(::grpc::ClientContext* context, const ::test::Request& request, ::test::Reply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::test::Reply>> AsyncTestGrpc(::grpc::ClientContext* context, const ::test::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::test::Reply>>(AsyncTestGrpcRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::test::Reply>> PrepareAsyncTestGrpc(::grpc::ClientContext* context, const ::test::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::test::Reply>>(PrepareAsyncTestGrpcRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::test::Reply>* AsyncTestGrpcRaw(::grpc::ClientContext* context, const ::test::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::test::Reply>* PrepareAsyncTestGrpcRaw(::grpc::ClientContext* context, const ::test::Request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status TestGrpc(::grpc::ClientContext* context, const ::test::Request& request, ::test::Reply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::test::Reply>> AsyncTestGrpc(::grpc::ClientContext* context, const ::test::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::test::Reply>>(AsyncTestGrpcRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::test::Reply>> PrepareAsyncTestGrpc(::grpc::ClientContext* context, const ::test::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::test::Reply>>(PrepareAsyncTestGrpcRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::test::Reply>* AsyncTestGrpcRaw(::grpc::ClientContext* context, const ::test::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::test::Reply>* PrepareAsyncTestGrpcRaw(::grpc::ClientContext* context, const ::test::Request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_TestGrpc_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status TestGrpc(::grpc::ServerContext* context, const ::test::Request* request, ::test::Reply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_TestGrpc : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_TestGrpc() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_TestGrpc() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TestGrpc(::grpc::ServerContext* context, const ::test::Request* request, ::test::Reply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTestGrpc(::grpc::ServerContext* context, ::test::Request* request, ::grpc::ServerAsyncResponseWriter< ::test::Reply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_TestGrpc<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_TestGrpc : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_TestGrpc() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_TestGrpc() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TestGrpc(::grpc::ServerContext* context, const ::test::Request* request, ::test::Reply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_TestGrpc : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_TestGrpc() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::test::Request, ::test::Reply>(std::bind(&WithStreamedUnaryMethod_TestGrpc<BaseClass>::StreamedTestGrpc, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_TestGrpc() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status TestGrpc(::grpc::ServerContext* context, const ::test::Request* request, ::test::Reply* response) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedTestGrpc(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::test::Request,::test::Reply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_TestGrpc<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_TestGrpc<Service > StreamedService;
};

}  // namespace test


#endif  // GRPC_test_2eproto__INCLUDED
